'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { isSupabaseConfigured, supabase, withTimeout } from '@/lib/supabase';
import { currency } from '@/lib/free-feature-utils';

function csvEscape(v: any) { return `"${String(v ?? '').replaceAll('"', '""')}"`; }

export default function AdminReportsPage() {
  const [orders, setOrders] = useState<any[]>([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; async function load(){ setLoading(true); try{ if(!isSupabaseConfigured || !supabase) throw new Error('Supabase is not connected.'); const {data,error}=await withTimeout(supabase.from('orders').select('*').order('created_at',{ascending:false}).limit(500),10000,'Reports orders'); if(error) throw error; if(active) setOrders(data||[]);}catch(e:any){ if(active) setError(e?.message || 'Failed to load reports.'); } finally{ if(active) setLoading(false); } } load(); return()=>{active=false}; }, []);
  const totals = useMemo(() => { const gross = orders.reduce((s,o)=>s+Number(o.grand_total || o.total_price || o.total || 0),0); const paid = orders.filter(o=>String(o.payment_status || '').toLowerCase()==='paid'); const paidGross = paid.reduce((s,o)=>s+Number(o.grand_total || o.total_price || o.total || 0),0); return { gross, paidGross, paid: paid.length }; }, [orders]);
  const download = () => { const rows = [['created_at','id','customer_email','payment_status','order_status','total','tracking_code'], ...orders.map(o=>[o.created_at,o.id,o.customer_email,o.payment_status,o.order_status,o.grand_total||o.total_price||o.total||0,o.tracking_code])]; const csv = rows.map(r=>r.map(csvEscape).join(',')).join('\n'); const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `exousia-sales-report-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); };
  return <main className="min-h-screen bg-[#0f0d0a] px-6 py-10 text-white"><div className="mx-auto max-w-7xl"><Link href="/admin" className="font-bold text-amber-400">← Back to admin</Link><div className="mt-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.3em] text-amber-400">Free reports</p><h1 className="mt-3 text-5xl font-black">Sales export reports</h1><p className="mt-3 text-white/60">Export orders to CSV without any paid analytics app.</p></div><button onClick={download} disabled={!orders.length} className="rounded-full bg-amber-700 px-6 py-3 font-black disabled:opacity-50">Download CSV</button></div>{error&&<p className="mt-6 rounded-2xl bg-red-950 p-4 font-bold text-red-100">{error}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-3xl bg-white/5 p-6"><p className="text-xs font-black uppercase text-white/40">Gross</p><p className="mt-2 text-3xl font-black">{currency(totals.gross)}</p></div><div className="rounded-3xl bg-white/5 p-6"><p className="text-xs font-black uppercase text-white/40">Paid sales</p><p className="mt-2 text-3xl font-black">{currency(totals.paidGross)}</p></div><div className="rounded-3xl bg-white/5 p-6"><p className="text-xs font-black uppercase text-white/40">Paid orders</p><p className="mt-2 text-3xl font-black">{totals.paid}</p></div></div><div className="mt-8 overflow-x-auto rounded-[2rem] border border-white/10 bg-white/5"><table className="w-full text-left text-sm"><thead><tr className="text-white/50"><th className="p-4">Date</th><th className="p-4">Customer</th><th className="p-4">Payment</th><th className="p-4">Status</th><th className="p-4 text-right">Total</th></tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-6 font-bold">Loading...</td></tr>:orders.slice(0,100).map(o=><tr key={o.id} className="border-t border-white/10"><td className="p-4">{o.created_at?new Date(o.created_at).toLocaleDateString():'-'}</td><td className="p-4">{o.customer_email || 'N/A'}</td><td className="p-4">{o.payment_status || 'pending'}</td><td className="p-4">{o.order_status || o.status || 'new'}</td><td className="p-4 text-right font-black">{currency(o.grand_total || o.total_price || o.total || 0)}</td></tr>)}</tbody></table></div></div></main>
}
