'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import Price from '@/components/Price';
import { supabase } from '@/lib/supabase';

export default function AnalyticsPage(){
 const[orders,setOrders]=useState<any[]>([]); const[products,setProducts]=useState<any[]>([]); const[msg,setMsg]=useState('Loading...');
 useEffect(()=>{(async()=>{ if(!supabase){setMsg('Supabase is not connected.');return;} const [o,p]=await Promise.all([supabase.from('orders').select('*').order('created_at',{ascending:false}),supabase.from('products').select('*')]); if(o.error||p.error)setMsg(o.error?.message||p.error?.message||'Load failed'); else{setOrders(o.data||[]);setProducts(p.data||[]);setMsg('');}})()},[]);
 const stats=useMemo(()=>{const revenue=orders.reduce((s,o)=>s+Number(o.total||o.subtotal||0),0);const units=orders.reduce((s,o)=>s+(Array.isArray(o.items)?o.items.reduce((a:any,i:any)=>a+Number(i.quantity||0),0):0),0);const low=products.filter(p=>Number(p.stock||0)<=10).length;return{revenue,units,low,orders:orders.length,avg:orders.length?Math.round(revenue/orders.length):0}},[orders,products]);
 const best=useMemo(()=>{const map=new Map<string,{name:string,qty:number,total:number}>();orders.forEach(o=>(o.items||[]).forEach((i:any)=>{const k=i.product_id||i.product_name;const cur=map.get(k)||{name:i.product_name||k,qty:0,total:0};cur.qty+=Number(i.quantity||0);cur.total+=Number(i.line_total||0);map.set(k,cur)}));return Array.from(map.values()).sort((a,b)=>b.qty-a.qty).slice(0,8)},[orders]);
 return <main className="min-h-screen bg-[#fbf7ef] px-6 py-12 text-stone-950 dark:bg-[#0f0d0a] dark:text-white"><div className="mx-auto max-w-7xl"><Link href="/admin" className="font-bold text-amber-800">← Back to admin</Link><h1 className="mt-6 text-5xl font-black">Sales analytics</h1>{msg&&<p className="mt-6 rounded-2xl bg-amber-100 p-4 font-bold text-amber-900 dark:bg-amber-500/10 dark:text-amber-100">{msg}</p>}<section className="mt-8 grid gap-5 md:grid-cols-5"><Stat label="Revenue" value={<Price amount={stats.revenue}/>}/><Stat label="Orders" value={stats.orders}/><Stat label="Units Sold" value={stats.units}/><Stat label="Average Order" value={<Price amount={stats.avg}/>}/><Stat label="Low Stock" value={stats.low}/></section><section className="mt-8 grid gap-8 lg:grid-cols-2"><div className="rounded-[2rem] bg-white p-6 shadow-sm dark:bg-white/5"><h2 className="text-2xl font-black">Best sellers</h2><div className="mt-5 space-y-3">{best.map(b=><div key={b.name} className="flex justify-between rounded-2xl bg-stone-100 p-4 dark:bg-white/10"><div><p className="font-black">{b.name}</p><p className="text-sm text-stone-500 dark:text-white/50">{b.qty} sold</p></div><Price amount={b.total} className="font-black"/></div>)}{best.length===0&&<p className="text-stone-500 dark:text-white/50">No sales yet.</p>}</div></div><div className="rounded-[2rem] bg-stone-950 p-6 text-white"><h2 className="text-2xl font-black">Action list</h2><ul className="mt-5 space-y-3 text-white/70"><li>• Restock products with 10 or fewer units.</li><li>• Review pending payment orders.</li><li>• Use coupon reports to test promotions.</li><li>• Export order rows from Supabase for accounting.</li></ul></div></section></div></main>;
}
function Stat({label,value}:{label:string;value:any}){return <div className="rounded-[2rem] bg-white p-6 shadow-sm dark:bg-white/5"><p className="text-sm font-bold text-stone-500 dark:text-white/50">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
